platform :ios, '14.1'
use_frameworks! :linkage => :static

target 'iosApp' do
  pod 'composeApp', :path => '../composeApp'
  pod 'Google-Mobile-Ads-SDK', '~> 12.3'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config.build_settings['GCC_ENABLE_OBJC_EXCEPTIONS'] = 'YES'
        # Needed for Compose Multiplatform
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
        config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -framework GoogleMobileAds'
      end
    end
  end
end