platform :ios, '14.1'
use_frameworks! :linkage => :static

target 'iosApp' do
    pod 'composeApp', :path => '../composeApp'
    pod 'Google-Mobile-Ads-SDK'
    pod 'GoogleMaps'
    pod 'Google-Maps-iOS-Utils'
end
